-- Typed models for the SpacexRest SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Capsule
---@field id? string
---@field land_landings? number
---@field last_update? string
---@field launches? table
---@field reuse_count? number
---@field serial? string
---@field status? string
---@field type? string
---@field water_landings? number

---@class CapsuleLoadMatch
---@field id string

---@class CapsuleListMatch
---@field id? string
---@field land_landings? number
---@field last_update? string
---@field launches? table
---@field reuse_count? number
---@field serial? string
---@field status? string
---@field type? string
---@field water_landings? number

---@class Core
---@field asds_attempts? number
---@field asds_landings? number
---@field block? number
---@field id? string
---@field last_update? string
---@field launches? table
---@field reuse_count? number
---@field rtls_attempts? number
---@field rtls_landings? number
---@field serial? string
---@field status? string

---@class CoreLoadMatch
---@field id string

---@class CoreListMatch
---@field asds_attempts? number
---@field asds_landings? number
---@field block? number
---@field id? string
---@field last_update? string
---@field launches? table
---@field reuse_count? number
---@field rtls_attempts? number
---@field rtls_landings? number
---@field serial? string
---@field status? string

---@class Crew
---@field agency? string
---@field id? string
---@field image? string
---@field launches? table
---@field name? string
---@field status? string
---@field wikipedia? string

---@class CrewLoadMatch
---@field id string

---@class CrewListMatch
---@field agency? string
---@field id? string
---@field image? string
---@field launches? table
---@field name? string
---@field status? string
---@field wikipedia? string

---@class Landpad
---@field details? string
---@field full_name? string
---@field id? string
---@field landing_attempts? number
---@field landing_successes? number
---@field latitude? number
---@field launches? table
---@field locality? string
---@field longitude? number
---@field name? string
---@field region? string
---@field status? string
---@field type? string
---@field wikipedia? string

---@class LandpadLoadMatch
---@field id string

---@class LandpadListMatch
---@field details? string
---@field full_name? string
---@field id? string
---@field landing_attempts? number
---@field landing_successes? number
---@field latitude? number
---@field launches? table
---@field locality? string
---@field longitude? number
---@field name? string
---@field region? string
---@field status? string
---@field type? string
---@field wikipedia? string

---@class Launch
---@field auto_update? boolean
---@field capsules? table
---@field core? string
---@field cores? table
---@field crew? table
---@field date_local? string
---@field date_precision? string
---@field date_unix? number
---@field date_utc? string
---@field details? string
---@field failures? table
---@field fairings? table
---@field flight? number
---@field flight_number? number
---@field gridfins? boolean
---@field id? string
---@field landing_attempt? boolean
---@field landing_success? boolean
---@field landing_type? string
---@field landpad? string
---@field launchpad? string
---@field legs? boolean
---@field links? table
---@field name? string
---@field net? boolean
---@field payloads? table
---@field reused? boolean
---@field rocket? string
---@field ships? table
---@field static_fire_date_unix? number
---@field static_fire_date_utc? string
---@field success? boolean
---@field tdb? boolean
---@field upcoming? boolean
---@field window? number

---@class LaunchLoadMatch
---@field id string

---@class LaunchListMatch
---@field auto_update? boolean
---@field capsules? table
---@field core? string
---@field cores? table
---@field crew? table
---@field date_local? string
---@field date_precision? string
---@field date_unix? number
---@field date_utc? string
---@field details? string
---@field failures? table
---@field fairings? table
---@field flight? number
---@field flight_number? number
---@field gridfins? boolean
---@field id? string
---@field landing_attempt? boolean
---@field landing_success? boolean
---@field landing_type? string
---@field landpad? string
---@field launchpad? string
---@field legs? boolean
---@field links? table
---@field name? string
---@field net? boolean
---@field payloads? table
---@field reused? boolean
---@field rocket? string
---@field ships? table
---@field static_fire_date_unix? number
---@field static_fire_date_utc? string
---@field success? boolean
---@field tdb? boolean
---@field upcoming? boolean
---@field window? number

---@class Launchpad
---@field details? string
---@field full_name? string
---@field id? string
---@field latitude? number
---@field launch_attempts? number
---@field launch_successes? number
---@field launches? table
---@field locality? string
---@field longitude? number
---@field name? string
---@field region? string
---@field rockets? table
---@field status? string

---@class LaunchpadLoadMatch
---@field id string

---@class LaunchpadListMatch
---@field details? string
---@field full_name? string
---@field id? string
---@field latitude? number
---@field launch_attempts? number
---@field launch_successes? number
---@field launches? table
---@field locality? string
---@field longitude? number
---@field name? string
---@field region? string
---@field rockets? table
---@field status? string

---@class Payload
---@field apoapsis_km? number
---@field arg_of_pericenter? number
---@field customers? table
---@field eccentricity? number
---@field epoch? string
---@field id? string
---@field inclination_deg? number
---@field launch? string
---@field lifespan_years? number
---@field longitude? number
---@field manufacturers? table
---@field mass_kg? number
---@field mass_lbs? number
---@field mean_anomaly? number
---@field mean_motion? number
---@field name? string
---@field nationalities? table
---@field norad_ids? table
---@field orbit? string
---@field periapsis_km? number
---@field period_min? number
---@field raan? number
---@field reference_system? string
---@field regime? string
---@field reused? boolean
---@field semi_major_axis_km? number
---@field type? string

---@class PayloadLoadMatch
---@field id string

---@class PayloadListMatch
---@field apoapsis_km? number
---@field arg_of_pericenter? number
---@field customers? table
---@field eccentricity? number
---@field epoch? string
---@field id? string
---@field inclination_deg? number
---@field launch? string
---@field lifespan_years? number
---@field longitude? number
---@field manufacturers? table
---@field mass_kg? number
---@field mass_lbs? number
---@field mean_anomaly? number
---@field mean_motion? number
---@field name? string
---@field nationalities? table
---@field norad_ids? table
---@field orbit? string
---@field periapsis_km? number
---@field period_min? number
---@field raan? number
---@field reference_system? string
---@field regime? string
---@field reused? boolean
---@field semi_major_axis_km? number
---@field type? string

---@class Roadster
---@field apoapsis_au? number
---@field details? string
---@field earth_distance_km? number
---@field earth_distance_mi? number
---@field eccentricity? number
---@field epoch_jd? number
---@field flickr_images? table
---@field id? string
---@field inclination? number
---@field launch_date_unix? number
---@field launch_date_utc? string
---@field launch_mass_kg? number
---@field launch_mass_lbs? number
---@field longitude? number
---@field mars_distance_km? number
---@field mars_distance_mi? number
---@field name? string
---@field norad_id? number
---@field orbit_type? string
---@field periapsis_arg? number
---@field periapsis_au? number
---@field period_days? number
---@field semi_major_axis_au? number
---@field speed_kph? number
---@field speed_mph? number
---@field video? string
---@field wikipedia? string

---@class RoadsterListMatch
---@field apoapsis_au? number
---@field details? string
---@field earth_distance_km? number
---@field earth_distance_mi? number
---@field eccentricity? number
---@field epoch_jd? number
---@field flickr_images? table
---@field id? string
---@field inclination? number
---@field launch_date_unix? number
---@field launch_date_utc? string
---@field launch_mass_kg? number
---@field launch_mass_lbs? number
---@field longitude? number
---@field mars_distance_km? number
---@field mars_distance_mi? number
---@field name? string
---@field norad_id? number
---@field orbit_type? string
---@field periapsis_arg? number
---@field periapsis_au? number
---@field period_days? number
---@field semi_major_axis_au? number
---@field speed_kph? number
---@field speed_mph? number
---@field video? string
---@field wikipedia? string

---@class Rocket
---@field active? boolean
---@field boosters? number
---@field company? string
---@field cost_per_launch? number
---@field country? string
---@field description? string
---@field diameter? table
---@field first_flight? string
---@field flickr_images? table
---@field height? table
---@field id? string
---@field mass? table
---@field name? string
---@field stages? number
---@field success_rate_pct? number
---@field type? string
---@field wikipedia? string

---@class RocketLoadMatch
---@field id string

---@class RocketListMatch
---@field active? boolean
---@field boosters? number
---@field company? string
---@field cost_per_launch? number
---@field country? string
---@field description? string
---@field diameter? table
---@field first_flight? string
---@field flickr_images? table
---@field height? table
---@field id? string
---@field mass? table
---@field name? string
---@field stages? number
---@field success_rate_pct? number
---@field type? string
---@field wikipedia? string

---@class Ship
---@field abs? number
---@field class? number
---@field course_deg? number
---@field home_port? string
---@field id? string
---@field image? string
---@field imo? number
---@field last_ais_update? string
---@field latitude? number
---@field launches? table
---@field legacy_id? string
---@field link? string
---@field longitude? number
---@field mass_kg? number
---@field mass_lbs? number
---@field mmsi? number
---@field model? string
---@field name? string
---@field roles? table
---@field speed_kn? number
---@field status? string
---@field type? string
---@field year_built? number

---@class ShipLoadMatch
---@field id string

---@class ShipListMatch
---@field abs? number
---@field class? number
---@field course_deg? number
---@field home_port? string
---@field id? string
---@field image? string
---@field imo? number
---@field last_ais_update? string
---@field latitude? number
---@field launches? table
---@field legacy_id? string
---@field link? string
---@field longitude? number
---@field mass_kg? number
---@field mass_lbs? number
---@field mmsi? number
---@field model? string
---@field name? string
---@field roles? table
---@field speed_kn? number
---@field status? string
---@field type? string
---@field year_built? number

---@class Starlink
---@field height_km? number
---@field id? string
---@field latitude? number
---@field launch? string
---@field longitude? number
---@field spaceTrack? table
---@field velocity_kms? number
---@field version? string

---@class StarlinkLoadMatch
---@field id string

---@class StarlinkListMatch
---@field height_km? number
---@field id? string
---@field latitude? number
---@field launch? string
---@field longitude? number
---@field spaceTrack? table
---@field velocity_kms? number
---@field version? string

local M = {}

return M
